Supported lnls-dig/fofb-ctrl-gw#1 changes
lnls-dig/halcs pull request #174
Opened 2022-03-14 15:57 UTC by guilhermerc

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +#define NUM_OF_NECESSARY_ARGS 4
```suggestion
enum necessary_args_idx {
  BOARD_SLOT,
  HALCS_NUMBER,
  CHANNEL,
  OP,
  NUM_OF_NECESSARY_ARGS
};
```

Assim ele se atualiza automaticamente, se vc precisar mudar algo.

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +    .broker_endp = strdup("ipc://"DFLT_BIND_FOLDER),
```suggestion
    .broker_endp = strdup("ipc://" DFLT_BIND_FOLDER),
```
Um teco mais fácil de ler

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +  };
Se você está inicializando tudo para zero, pode omitir o `.verbose`, a não ser que queira ser explícito. E pode colocar `nec_args = {0};` também.

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +        opt_args.broker_endp = strdup(optarg);
Como conversamos, strdup com `optarg` não é necessário.

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +        nec_args.is_given[BOARD_SLOT] = true;
Aqui e em outros pontos você não está resetando e verificando `errno` após a conversão. `strtoul` pode retornar 0 para entradas inválidas. Acho que para argumentos é menos relevante, mas é bom lembrar.

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +              " while trying to open %s\n", optarg);
Dá pra imprimir `strerror(errno)` aqui para ajudar o usuário, o que você acha?

Dá pra evitar digitar tudo isso usando o especificador de formato `%m`, mas que eu me lembre não é padrão em nenhum standard ainda.

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +                  coeffs.data[i] = strtoul(coeff, NULL, 10);
Acho que aqui é importante tratar erros de `strtoul`

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +                if(fgets(coeff, 20, fp) != NULL) {
```suggestion
                if(fgets(coeff, sizeof coeff, fp) != NULL) {
```

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +                  goto err_free_mem;
Não importa tanto, já que você está saindo do programa quando isso acontece, mas o arquivo não está sendo fechado.

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +        }
```suggestion
        i < FOFB_PROCESSING_REGS_RAM_BANK_SIZE/sizeof(uint32_t) - 1; i++) {
        fprintf(stdout, "%d, ", coeffs.data[i]);
      }
      fprintf(stdout, "%d", coeffs.data[i]);
```

Me parece um pouco mais limpo? Aí declara `int i` fora do for para funcionar.

2022-03-21 13:54 UTC, ericonr commented on examples/src/fofb_processing.c
> +        }
Um detalhe que não sei se importa é que imprimir com  `GET_COEFF` não gera um arquivo que vc possa ler de volta depois, né?

2022-03-21 13:54 UTC, ericonr commented on include/hw/wb_fofb_processing_regs.h
> + #endif
Espaço extra

2022-03-21 13:54 UTC, ericonr commented on src/client/src/halcs_client_core.c
> +        "[halcs_fofb_processing_coeff_ram_bank_read] Something wrong hapenned",
```suggestion
        "[halcs_fofb_processing_coeff_ram_bank_read] Something wrong happened",
```

2022-03-21 13:54 UTC, ericonr commented on src/client/src/halcs_client_core.c
> +        FOFB_PROCESSING_NAME_COEFF_RAM_BANK_READ, service, &input, output);
```suggestion
        FOFB_PROCESSING_NAME_COEFF_RAM_BANK_READ, service, &input, coeffs->data);
```

Para evitar a cópia?

2022-03-21 13:54 UTC, ericonr commented on src/sm_io/modules/fofb_processing/sm_io_fofb_processing_exp.c
> +static int _fofb_processing_coeff_ram_bank_read (void *owner, void *args,
Estilo: funções estáticas não precisam de `_` no começo como namespacing

2022-03-21 13:54 UTC, ericonr commented on src/sm_io/modules/fofb_processing/sm_io_fofb_processing_exp.c
> +        memcpy(ret, coeffs.data, FOFB_PROCESSING_REGS_RAM_BANK_SIZE);
Pular a cópia também é uma opção, né? Usar `ret` diretamente no `smio_thsafe_client_read_block`

2022-03-21 18:02 UTC, guilhermerc commented on examples/src/fofb_processing.c
> +                  goto err_free_mem;
Conforme conversamos, o arquivo está sendo fechado.

2022-03-21 18:50 UTC, guilhermerc commented on src/sm_io/modules/fofb_processing/sm_io_fofb_processing_exp.c
> +static int _fofb_processing_coeff_ram_bank_read (void *owner, void *args,
Perfeito, aqui só procurei manter a consistência com os outros módulos...

2022-03-21 19:19 UTC, guilhermerc commented on examples/src/fofb_processing.c
> +        }
Sim, de fato. Tal implementação ajudaria a scriptar um teste de escrita/leitura fazendo diff dos arquivos, né?
Vou deixar essa conversa em aberto e futuramente implemento.

2022-03-25 19:08 UTC, melissa-aguiar reviewed
Code reviwed and no changes suggested

2022-08-29 18:22 UTC, Palmitoxico requested changes

2022-08-29 18:22 UTC, augustofg commented on examples/src/fofb_processing.c
> +#include "hw/wb_fofb_processing_regs.h" // TODO: Is this include okay to be here?
Still necessary?

2022-08-29 19:12 UTC, guilhermerc commented on examples/src/fofb_processing.c
> +#include "hw/wb_fofb_processing_regs.h" // TODO: Is this include okay to be here?
Nope. Removed on e03c75135f2d685f1f5710aaab048dc2aa66e25b.

2022-08-29 19:13 UTC, guilhermerc commented on examples/src/fofb_processing.c
> +        }
Implementado!

2022-08-30 12:23 UTC, merged